version: "3"

services:
  backend:
    build:
      context: ../backend/.
    environment:
      - JWT_SECRET=sssshhhh
    ports:
      - "3000:3000"
    networks:
      - vuejs_network
  dashboard:
    build:
      context: ../dashboard
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - vuejs_network

networks:
  vuejs_network:
    driver: bridge
